image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY #what are these? where do they come from?

variables:
  DOCKER_HOST: tcp://localhost:2375
  IMAGE_DEVL_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_JOB_ID
  IMAGE_PROD_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME


build-branch:
  stage: build
  only:
    - branches
    - master
  script:
  - docker build -t $IMAGE_DEVL_NAME
  - docker push $IMAGE_DEVL_NAME

build-tag:
  stage: build
  only:
    - tags
  script:
  - docker build -t $IMAGE_PROD_NAME .
  - docker push $IMAGE_PROD_NAME
