image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  IMAGE_DEVL_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_JOB_ID
  IMAGE_PROD_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  registry: quay.io
  repo_name: container-fluent-bit
  QUAY_ORG: SECRET 
  QUAY_USER: SECRET 
  QUAY_ROBOT: SECRET 
  QUAY_PASSWORD: SECRET


stages:
  - build
  - test
  - publish

build-branch:
  stage: build
  only:
    - branches
  except:
    - master
  script:
  - docker build -t $IMAGE_DEVL_NAME .
  - docker push $IMAGE_DEVL_NAME

build-master:
  stage: build
  only:
    - master
  script:
  - docker build -t $IMAGE_PROD_NAME .
  - docker push $IMAGE_PROD_NAME

publish-master:
  stage: publish
  only:
    - master
  script:
  - docker pull $IMAGE_PROD_NAME
  - docker login ${registry} -u ${QUAY_USER}+${QUAY_ROBOT} -p ${QUAY_PASSWORD}
  - docker tag ${IMAGE_PROD_NAME} ${registry}/${QUAY_ORG}/${repo_name}:gitlab_test
  - docker push ${registry}/${QUAY_ORG}/${repo_name}:gitlab_test