image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  IMAGE_DEVL_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_JOB_ID
  IMAGE_PROD_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  registry: quay.io
  image_name: fluent-bit-container
  quay_org: samsung_cnct
  QUAY_ROBOT: SECRET 
  QUAY_PASSWORD: SECRET

stages:
  - build
  - test
  - publish
  - cleanup

build-branch:
  stage: build
  only:
    - branches
  except:
    - master
  script:
  - docker build -t $IMAGE_DEVL_NAME .
  - docker push $IMAGE_DEVL_NAME

build-master:
  stage: build
  only:
    - master
    - tags
  script:
  - docker build -t $IMAGE_PROD_NAME .
  - docker push $IMAGE_PROD_NAME

# test:
#    stage: test

publish-master:
  stage: publish
  only:
    - master
  script:
  - docker pull $IMAGE_PROD_NAME
  - docker login ${registry} -u ${quay_org}+${QUAY_ROBOT} -p ${QUAY_PASSWORD}
  - docker tag ${IMAGE_PROD_NAME} ${registry}/${quay_org}/${image_name}:latest
  - docker push ${registry}/${quay_org}/${image_name}:latest

publish-version-tag:
  stage: publish
  only:
    - /v[0-9]+\.[0-9]+(\.[0-9]+[a-z]?)?/
  script:
  - docker pull $IMAGE_PROD_NAME
  - docker login ${registry} -u ${quay_org}+${QUAY_ROBOT} -p ${QUAY_PASSWORD}
  - docker tag ${IMAGE_PROD_NAME} ${registry}/${quay_org}/${image_name}:$CI_COMMIT_TAG
  - docker push ${registry}/${quay_org}/${image_name}:$CI_COMMIT_TAG

cleanup-branch-image:
  stage: cleanup
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_PROJECT: $CI_PROJECT_PATH
    DOCKER_TAG: $CI_COMMIT_REF_NAME-$CI_JOB_ID
  only:
    - branches
  except:
    - master
  when: always
  allow_failure: true
  script:
  - echo "Unicorns Are Deleting ${DOCKER_REGISTRY}/${DOCKER_PROJECT}/${DOCKER_TAG}"
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
  - export DOCKER_ETAG=$(docker-registry-curl -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -X GET "https://${DOCKER_REGISTRY}/v2/${DOCKER_PROJECT}/manifests/${DOCKER_TAG}" -si | egrep -e "^Etag: " | cut -d " " -f2 | tr -d \" | sed 's/\r//')
  - echo "Attempting to remove ${DOCKER_ETAG}"
  - docker-registry-curl -D - -sL -X DELETE "https://${DOCKER_REGISTRY}/v2/${DOCKER_PROJECT}/manifests/${DOCKER_ETAG}"
